export enum ExceptionTypeKeys {
  BAD_MODEL = 'BadModelException',
  INVALID_PERMISSIONS = 'InvalidPermissionsException',
  NOT_FOUND = 'NotFoundException',
  UNEXPECTED = 'UnexpectedException',
}

export enum ErrorCodesKeys {
  UNIMPLEMENTED = 'TST000',

  // ...
  REPOSITORY_UNEXPECTED = 'TST010',

  REQUEST_NOT_VALID = 'TST020',
  ID_FORMAT_NOT_VALID = 'TST021',
  DESCRIPTION_TOO_LARGE = 'TST022',
  USER_ID_FORMAT_NOT_VALID = 'TST023',
  AMOUNT_EXCEEDS_BUDGET = 'TST025',
  AUTH_HEADER_NOT_PROVIDED = 'TST028',

  TRANSACTION_NOT_FOUND = 'TST030',
  BUDGET_NOT_FOUND = 'TST031',

  TOKEN_NOT_VALID = 'TST040',
  USER_NOT_AUTHENTICATED = 'TST041',
}
